Consolidate BrowserAuthCallbackHandler and BrowserAuthorizationClient
iTwin/auth-clients pull request #123
Opened 2023-03-07 17:11 UTC by ben-polinsky

Merge BrowserAuthCallbackHandler into BrowserAuthorizationClient

2023-03-07 17:12 UTC, ben-polinsky commented
I've tested this out using the integration tests in #119 and they pass, FYI

2023-03-07 21:49 UTC, aruniverse reviewed
thx for killing off the static

2023-03-07 21:49 UTC, aruniverse commented
> I've tested this out using the integration tests in #119 and they pass, FYI

lets get that pr merged in before this

2023-03-08 23:29 UTC, aruniverse commented on packages/browser/src/Client.ts
> +    try {
these 2 try blocks will do the same thing.
previously the handler would try to check both type of response modes (query & fragment)
callbackInternal should probably take an arg for response mode, which can then be used to determine the urlSuffix and do the actual signin callback

2023-03-09 14:18 UTC, ben-polinsky commented on packages/browser/src/Client.ts
> +    try {
Right, my mistake - may have been a vestige of me trying to figure out the silent callback and fiddling around. Thanks for catching this.

2023-03-09 15:06 UTC, ben-polinsky commented on packages/browser/src/Client.ts
> +    try {
Okay fixed.

2023-03-09 17:45 UTC, evelynpreslar-bentley commented on packages/browser/README.md
> +  await client.signInSilent();
It's not necessary to call `signInSilent` before `signInRedirect`, since the latter attempts a non-interactive signin first (and that behavior is documented on `signInRedirect`)

That behavior can be skipped with certain `prompt` arguments, but it might be valuable to simplify this example by removing the `signInSilent` and the try-catch?
As written, this code will attempt to 2 silent signins in a row, which is redundant in all cases.

2023-03-09 19:01 UTC, ben-polinsky commented on packages/browser/README.md
> +  await client.signInSilent();
Yes, thanks - that makes sense.

2023-03-14 14:36 UTC, WillGrayMSU approved these changes

2023-03-14 14:37 UTC, aruniverse commented
@WillGrayMSU did you pull this into DR and test in a CoSpace to verify this worked fine?

2023-03-14 14:44 UTC, WillGrayMSU commented
> @WillGrayMSU did you pull this into DR and test in a CoSpace to verify this worked fine?

I haven't, but I can try now

2023-03-15 20:36 UTC, WillGrayMSU requested changes
types need to be exported

2023-03-15 20:37 UTC, ben-polinsky commented on packages/browser/src/index.ts
Ah - thanks

2023-03-15 20:47 UTC, ben-polinsky commented on packages/browser/src/index.ts
there you are

2023-03-16 12:07 UTC, WillGrayMSU commented on packages/browser/src/index.ts
Perfect, thanks!

2023-03-16 12:07 UTC, WillGrayMSU approved these changes

2023-03-21 16:20 UTC, ben-polinsky commented
@aruniverse I'm unable to test the cra-template due to some annoying pre-release/peer deps constraints. Perhaps we should publish this as a pre-release or alpha to test.

2023-03-21 17:58 UTC, aruniverse approved these changes
getting a pre-release out will be annoying, since the change is marked as minor and its currently 0.x, no one should be pulling this in automatically. i guess we can test once released

2023-03-21 18:03 UTC, aruniverse commented
> > getting a pre-release out will be annoying, since the change is marked as minor and its currently 0.x, no one should be pulling this in automatically. i guess we can test once released
> 
> Maybe it should be major... it's a breaking change

according to semver, breaking changes are allowed in 0.x

2023-03-21 18:04 UTC, ben-polinsky commented
> > > getting a pre-release out will be annoying, since the change is marked as minor and its currently 0.x, no one should be pulling this in automatically. i guess we can test once released
> > 
> > 
> > Maybe it should be major... it's a breaking change
> 
> according to semver, breaking changes are allowed in 0.x

the more you know! Thanks

2023-03-21 18:07 UTC, merged