Update certa dependency so that ARM processors are supported
iTwin/auth-clients pull request #81
Opened 2022-08-06 00:39 UTC by anmolshres98

2022-08-06 01:52 UTC, aruniverse approved these changes

2022-08-06 01:52 UTC, aruniverse commented on common/changes/@itwin/oidc-signin-tool/as-update-certa-dependency_2022-08-06-00-15.json
> +      "type": "patch"
I'm thinking minor bump for this? And then patch when the official 3.4 release is out?

2022-08-06 18:33 UTC, anmolshres98 commented on common/changes/@itwin/oidc-signin-tool/as-update-certa-dependency_2022-08-06-00-15.json
> +      "type": "patch"
That's alright by me

2022-08-07 21:20 UTC, calebmshafer requested changes

2022-08-07 21:20 UTC, calebmshafer commented on packages/oidc-signin-tool/package.json
> +    "@itwin/certa": "3.4.0-dev.3",
I don't think we should lock down the specific version here. Can we backport the change to 3.3.0 instead?

2022-08-08 01:35 UTC, anmolshres98 commented on packages/oidc-signin-tool/package.json
> +    "@itwin/certa": "3.4.0-dev.3",
Gothcha, just made a [PR}(https://github.com/iTwin/itwinjs-core/pull/4039) for the backport

2022-08-08 16:21 UTC, calebmshafer commented on packages/oidc-signin-tool/package.json
> +    "@itwin/certa": "3.4.0-dev.3",
Agreed, however I wasn't sure about bumping this as a minor version and then patching it to move to the new minor release.

2022-08-08 16:24 UTC, aruniverse commented on packages/oidc-signin-tool/package.json
> +    "@itwin/certa": "3.4.0-dev.3",
Can we break locktstep for these tooling pkgs like certa?

2022-08-08 16:30 UTC, calebmshafer commented on packages/oidc-signin-tool/package.json
> +    "@itwin/certa": "3.4.0-dev.3",
we should, let's add it to the backlog.

2022-08-08 19:30 UTC, anmolshres98 commented
Drafting till 3.3 release of core

2022-08-18 20:53 UTC, anmolshres98 commented
@aruniverse @calebmshafer should be ready for review now

2022-08-18 20:55 UTC, aruniverse commented
I dont think we need this pr, if it's going to automatically pull in certa@^3.0, which should pull in 3.3.0

2022-08-18 21:09 UTC, aruniverse commented
closing as is we use ^3.0.0 in oidc-client-tool so should pull in the latest ver of puppeteer

2022-08-18 21:09 UTC, closed without merging